### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by kotarou3** [smogon/pokemon-showdown#1503] opened 2015-02-03 10:11 UTC
The server should support both IPv4 and IPv6.
Banning and locking code will need to be updated to support them.

**Comment by kotarou3** [comment] 2015-02-03 10:22
I'm currently thinking of implementing an IP list class similar to how a network router would work: by having a sorted list of IP prefixes and binary searching over the list, and the longest prefix is returned when there is more than a single match.

The class would have one such list for each of IPv4 and IPv6. IPv4 addresses mapped as IPv6 addresses would be automatically be converted back to IPv4.  
This class would also replace the existing `cidr.js`

Time complexity (ignoring JIT optimisations):
* Lookup: O(log N)
* Insertion and Deletion: O(N)

Memory complexity: O(N)

**Comment by kotarou3** [comment] 2015-02-03 10:57
Alternatively, this could be done using red-black trees for O(log N) insertion and deletion.
I won't be writing a RB-tree implementation though, so that would require pulling another dependency

**Comment by Zarel** [comment] 2015-02-03 20:54
Does SockJS support IPv6? I was operating under the assumption that it didn't.

**Comment by kotarou3** [comment] 2015-02-04 06:48
I believe it does, since I think I ran a small IPv6 test for tbt once and it worked without problems (other than bans/locks not working properly).
Other than that, IPv6 can also be exposed via a reverse proxy, where the proxy handles everything IPv6, with the only evidence that the connection was IPv6 is in the X-Forwarded-For header

**Comment by Zarel** [comment] 2015-02-05 18:34
Sadly, I don't have IPv6 support so I can't test this.

**Comment by kotarou3** [comment] 2015-02-05 18:51
Most computers have it enabled by default for localhost (::1).
Just swap out the bind IP in sockets.js with `::` and try connecting to either http://ip6-localhost.psim.us/ (Should get an IP of `::1`) or http://localhost.psim.us/ (Should get an IP of `::ffff:127.0.0.1`)

I just tested it just then and it worked fine.

**Comment by kotarou3** [comment] 2015-02-13 13:41
After thinking about it further, neither of my initial solutions would work correctly (or at least with good performance).

Instead, I've created a npm module (https://www.npmjs.com/package/ip-router) that does it properly with a patricia tree.

Insertion, Deletion, Lookup are all `O(P)` where `P` is the prefix length for the IP subnet (Typically `32` for IPv4 and `64` for IPv6)

**Comment by kotarou3** [comment] 2015-02-13 16:03
I'm waiting for #1471 to be pulled first so I don't create any conflicts while implementing this

**Comment by kotarou3** [comment] 2015-06-14 07:42
Some notes on banning/locking:
 - Will default to a /64, since ISPs will give out at least a /64 to each customer, and typical consumer routers don't support prefix delegation, so they will only use a single /64 if allocated more than that.
 - For the few evaders who know how to change to other /64s in their allocation, that can be solved by what we do currently for "router resetting" evaders - a range ban, but a /56 or /48 depending on the ISP's allocation size
 - Will be more "accurate", since ISPs will likely not give dynamic IPv6 subnets, so a well placed range ban will only ban the user and nobody else from that ISP

**Comment by xfix** [comment] 2015-06-14 08:29
Banning a range by default is a good idea, but I'm not entirely sure if it's a good idea now that I think about it. For example, in schools, an user may have an unique IPv6 address, and banning an entire range could as well ban an entire school when it's not needed (this is how currently bans work with IPv4, but if school is nice enough to provide unique IPv6 addresses, why not use that to restrict ban impact?).

Second, a user may not necessarily have /64 allocation. While indeed, it's recommended for users to have allocation of that size (because certain IPv6 features don't work with smaller allocations), some stupid ISPs think that they are going to make smaller allocations because why not. For example, Comcast says "We will allocate a single IPv6 address (/128), since we know that only a single device is connecting, with no additional need to sub-net." What is this, I don't even... Although, this is The Worst Company of America according to Consumerist in 2014, so perhaps I shouldn't be surprised.

Third, /64 is minimal recommended allocation, but [RFC6177](https://tools.ietf.org/html/rfc6177) actually recommends /56 in order to let subscribers make subnets in their allocation ([RFC3177](https://tools.ietf.org/html/rfc3177) recommended /48, but that was obsoleted by RFC6177). If abuser's ISP provides /56, avoiding a ban on /64 range is very easy if somebody insists.

Evasion caused by changing IP within a an allocation (if somebody knows how to do that, most people won't) could be dealt with with manual range lock anyway.

**Comment by kotarou3** [comment] 2015-06-14 10:00
The main problem that leads me to want to ban a /64 by default is because of [privacy extensions](https://en.wikipedia.org/wiki/IPv6#Privacy), which is enabled by default on the majority of OSes.
Simply resetting your network connection _to the device_, not router, will give you a completely different address. This makes it far faster and easier to change IPv6 addresses (within the /64) than with the old "reset router" method.

For your second point, that appears to be true, but also seems to be being phased out at the same time.
From one of my server logs, approximately 1.5k unique /64 and 5.5k unique /72 prefixes have connected in the past. Of that:
 - AT&T or Comcast IPs
   - 600 /64s
   - 4k /72s have connected only for _one or two_ days
   - 150 /72s have connected for three or more days
 - In general
   - 5.3k /72s have connected only for one or two days
   - 200 /72s have connected for three or more days

As for your third point, that was addressed by my earlier first and second points. Consumer routers don't do prefix delegation, so by default they will pick the first /64 in the range allocated to them and only use that.

**Comment by xfix** [comment] 2015-06-14 10:09
Okay, that is convincing. If you don't need any special configuration to get a new IPv6 address, it's probably better to ban /64.

**Comment by kotarou3** [comment] 2015-06-14 10:26
One possible compromise would be checking if the latter 64 bits is a valid EUI-64 address, and if it is, ban just the /128 instead of the full /64.
Though, a grand total of 21 IPv6 addresses connected so far (out of the 1.5k /64s) have used an EUI-64 address...

**Comment by kotarou3** [comment] 2015-06-15 11:42
@Joimer @Slayer95 @monsanto 
Any opinions/comments on the above?

**Comment by Zarel** [comment] 2015-06-15 19:02
I'm still skeptical that it won't make it significantly easier to evade.

**Comment by Zarel** [comment] 2015-06-15 19:02
I guess we can revisit this after I'm done with timed locks, though.

**Comment by kotarou3** [comment] 2015-06-16 01:48
What are you skeptical about? I'll address your concerns directly

**Comment by Zarel** [comment] 2015-06-16 03:14
Do we have any documentation that blocking a `/64` will block a user?

**Comment by monsanto** [comment] 2015-06-16 04:12
Considering that IPv6 doesn't actually solve any problems for us, my initial opinion is :-1: if its support makes life even marginally more difficult for our moderators.

**Comment by kotarou3** [comment] 2015-06-16 04:42
@Zarel 
http://stackoverflow.com/questions/10967534/rate-limiting-banning-ips-in-ipv6
http://serverfault.com/questions/258466/how-are-ip-based-rules-eg-bans-filters-affected-once-ipv6-becomes-the-standar
Also, the RFC @xfix linked.
Almost all sources point to end-users being allocated either a /64 or /56.

As for banning a /64 rather than /128, see the above discussion with xfix.

All end-user equipment in their default configuration only ever use the first /64 in their allocated subnet. This is unlikely to change for a long time, since using more than a single /64 at once would require a prefix delegation server on the router and a prefix delegation client on the connecting device.
All the consumer routers I've seen that support IPv6 (at least 5 different brands in the past year), do not come with a prefix delegation server.
Windows by default has its prefix delegation client turned off.

For the few smart people that evade by changing /64s in their larger (e.g., /56) allocations, they can be treated the same as people who currently do the "restart router" trick to evade - a range ban, but this time on a /56.
Changing /64s within your allocation is *hard*, since it always involves some manual configuration of your router - harder than simply restarting it. That's also compounded by the fact that most IPv6-capable consumer routers don't even have a configuration option for it in their GUIs.

Note that some ISPs are giving out dynamic IPv6 addresses (e.g., comcast), but these can be treated no differently than current dynamic IPv4 addresses.

**Comment by panpawn** [comment] 2016-07-22 05:51
>I guess we can revisit this after I'm done with timed locks, though.

Can we revisit it now, @Zarel?

**Comment by Zarel** [comment] 2016-07-22 07:10
Is this actually important to anyone? @_@

**Comment by Zarel** [comment] 2016-07-22 07:11
If someone pullreqs with IPv6 disabled by default, I'd accept it..

**Comment by panpawn** [comment] 2017-05-28 01:07
@Zarel - does that mean that you'd have it disabled on Main?

**Comment by panpawn** [comment] 2017-05-28 01:13
Also, @kotarou3 - is this something you were still interested in doing?

**Comment by Zarel** [comment] 2017-05-28 05:30
Yes, I'd want it disabled on Main.

Like, banning /64's solves _some_ issues, but not all of them, and in general it'd be nice to be able to test on other servers before doing too much to it.

**Comment by Morfent** [comment] 2017-05-28 09:27
Note: in case the sockets rewrite gets merged, configuring the Go servers to accept both IPv4 and IPv6 connections is simple: just replace any instance of `"tcp4"` with `"tcp"` in `sockets/main.go`. No other changes to the Go files are necessary

**Comment by monsanto** [comment] 2023-01-07 04:22
I have no desire to run IPv6 on main. Someone would have to convince me that we have something to gain by doing so. If someone wanted to send a patch for IPv6 support they'd have to convince me that it wouldn't be a maintenance burden. I don't want to accept something that will just bitrot.

**Closed by monsanto** 2023-01-07 04:22 UTC
Labels: enhancement, discussion
