### ISSUE TITLE
The move "metal burst" crashes the battle system.

### ISSUE THREAD

**Issue by iWiggins** [smogon/pokemon-showdown#7967] opened 2021-01-30 05:35 UTC
The battle engine crashes whenever the move "Metal Burst" is used.

Details:

![showdown-bug](https://user-images.githubusercontent.com/7118298/106348203-b14f4e80-6281-11eb-825f-59e890a2fe15.PNG)

```
A battle crashed: TypeError: source.getLastDamagedBy is not a functionat Battle.onModifyTarget (/opt/Pokemon-Showdown/pokemon-showdown/.data-dist/moves.js:10912:33)
at Battle.runEvent (/opt/Pokemon-Showdown/pokemon-showdown/.sim-dist/battle.js:741:34)
at Battle.useMoveInner (/opt/Pokemon-Showdown/pokemon-showdown/.data-dist/scripts.js:175:25)
at Battle.useMove (/opt/Pokemon-Showdown/pokemon-showdown/.data-dist/scripts.js:141:27)
at Battle.runMove (/opt/Pokemon-Showdown/pokemon-showdown/.data-dist/scripts.js:96:33)
at Battle.runAction (/opt/Pokemon-Showdown/pokemon-showdown/.sim-dist/battle.js:2576:9)
at Battle.go (/opt/Pokemon-Showdown/pokemon-showdown/.sim-dist/battle.js:2765:9)
at Battle.commitDecisions (/opt/Pokemon-Showdown/pokemon-showdown/.sim-dist/battle.js:2831:8)
at Battle.choose (/opt/Pokemon-Showdown/pokemon-showdown/.sim-dist/battle.js:2787:35)
at RoomBattleStream._writeLine (/opt/Pokemon-Showdown/pokemon-showdown/.sim-dist/battle-stream.js:119:17)
```

Steps to Reproduce:

- Add a pokemon to a team with the move metal burst.
- Begin a generation 8 battle with that team.
- Use the move Metal Burst after being hit by a move.

**Comment by Zarel** [comment] 2021-01-31 01:50
We have unit tests for Metal Burst and they seem to be working fine.

Can you send an inputlog `/exportinputlog` or upload a replay on the official site?

**Comment by iWiggins** [comment] 2021-01-31 05:32
Here's the log:
```
>version 2e4a0b4405ef876064f9f39b3d4438dfeba15819
>start {"formatid":"gen8customgame","seed":[25330,52912,50769,351]}
>player p1 {"name":"LID919","avatar":"steven","team":"Claydol||lightclay|levitate|reflect,lightscreen,toxic,bodypress|Bold|252,,252,,4,||,0,,,,0|||]Skarmory||aguavberry|weakarmor|swordsdance,bravebird,doubleedge,nightslash|Adamant|232,252,,,,24|||||]Cradily||bigroot|stormdrain|amnesia,curse,stoneedge,gigadrain|Quiet|252,252,,,,||,,,,,0|||]Armaldo||choiceband|battlearmor|aquajet,earthquake,superpower,xscissor|Adamant|252,252,,,4,|||||]Aggron||figyberry|sturdy|metalburst,bodypress,dragontail,meteorbeam|Relaxed|252,,252,4,,||,,,,,0|||]Metagross||assaultvest|clearbody|bulletpunch,brickbreak,psychocut,explosion|Adamant|252,252,,,4,|||||","rating":0}
>player p2 {"name":"Crooked_Sinner","avatar":"harlequin","team":"Whimsicott||rockyhelmet|prankster|memento,toxic,switcheroo,trickroom|Relaxed|252,,252,,4,||,0,,,,|||]Greedent||sitrusberry|cheekpouch|bodyslam,earthquake,icefang,bellydrum|Adamant|252,,104,,152,|||||]Hawlucha||psychicseed|unburden|acrobatics,closecombat,thunderpunch,swordsdance|Adamant|,252,,,4,252|||||]Indeedee|indeedeef|choicespecs|psychicsurge|expandingforce,psychic,mysticalfire,healingwish|Timid|,,,252,4,252|F|,0,,,,|||]Pincurchin||terrainextender|electricsurge|risingvoltage,charge,suckerpunch,recover|Relaxed|252,4,252,,,|||||]Raichu|raichualola|focussash|surgesurfer|expandingforce,risingvoltage,extremespeed,nastyplot|Hasty|,4,,252,,252|||||","rating":0}
>p1 team 5, 2, 3, 4, 1, 6
>p2 team 4, 2, 3, 1, 5, 6
>p1 move metalburst
>p2 move expandingforce
```

**Comment by Zarel** [comment] 2021-01-31 06:10
I'm not getting a crash:

```
|player|p1|LID919|steven|
|player|p2|Crooked_Sinner|harlequin|
|teamsize|p1|6
|teamsize|p2|6
|gametype|singles
|gen|8
|tier|[Gen 8] Custom Game
|clearpoke
|poke|p1|Claydol|
|poke|p1|Skarmory, M|
|poke|p1|Cradily, F|
|poke|p1|Armaldo, M|
|poke|p1|Aggron, F|
|poke|p1|Metagross|
|poke|p2|Whimsicott, F|
|poke|p2|Greedent, M|
|poke|p2|Hawlucha, M|
|poke|p2|Indeedee-F, F|
|poke|p2|Pincurchin, M|
|poke|p2|Raichu-Alola, M|
|teampreview|24
|
|t:|1612073401
|start
|switch|p1a: Aggron|Aggron, F|344/344
|switch|p2a: Indeedee|Indeedee-F, F|281/281
|-fieldstart|move: Psychic Terrain|[from] ability: Psychic Surge|[of] p2a: Indeedee
|turn|1
|
|t:|1612073401
|move|p2a: Indeedee|Expanding Force|p1a: Aggron
|debug|psychic terrain boost
|debug|terrain buff
|-resisted|p1a: Aggron
|-damage|p1a: Aggron|107/344
|move|p1a: Aggron|Metal Burst|p2a: Indeedee
|-damage|p2a: Indeedee|0 fnt
|faint|p2a: Indeedee
|
|upkeep
```

Are you sure you're on the latest version?

**Comment by Zarel** [comment] 2021-01-31 06:11
I'm not getting a crash on the exact version in your log, for that matter.

I think you might have uncommitted changes that interfere with it?

**Comment by Zarel** [comment] 2021-01-31 06:12
(Closing because I've confirmed it's not a bug in our code; but feel free to continue discussing your problem here.)

**Closed by Zarel** 2021-01-31 06:11 UTC

**Comment by iWiggins** [comment] 2021-01-31 19:14
I pulled the latest code and the bug has vanished.
